trigger:
- main

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: "Install Node.js"

- script: |
    npm install -g @angular/cli
  displayName: 'Install Angular CLI'

- script: |
    npm install 
  displayName: 'Install npm'

- task: Npm@1
  inputs: 
    command: custom  
    verbose: false  
    customCommand: 'run build'
  displayName: Build
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
        npm | "$(Agent.OS)"
    path: $(npm_config_cache)
  displayName: Cache npm
- script: npm clean install 

- task: Npm@1
  inputs:
    command: custom
    customCommand: 'run build'
  displayName: Build  
- task : CopyPublishBuildArtifacts@1
  inputs:  
        CopyRoot: /dist  
        Contents: '**'  
        ArtifactName: angular-web-app 
        ArtifactType: Container
