trigger:
- main

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: "Install Node.js"
- task: Npm@1  
  inputs:  
    command: custom
    verbose: false
    customCommand: 'install -g @angular/cli@13.2.5'
  displayName: 'Install Angular CLI'
- task: Npm@1  
  inputs:
    command: custom  
    customCommand: 'install file:custom-angular-lib.tgz --legacy-peer-deps' 
  displayName: 'install npm'

- task: Npm@1
  inputs: 
    command: custom  
    verbose: false  
    customCommand: 'run build'
  displayName: 'Build'
  