trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: "Install Node.js 12.x"

- task: Npm@1
  inputs:
    command: custom
    customCommand: 'install @angular/cli@7.3.1'
    workingDir: $(System.DefaultWorkingDirectory)
    verbose: false
  displayName: 'Install Angular CLI' 

- task: Npm@1
  displayName: 'install npm'
  inputs:
    workingDir: $(System.DefaultWorkingDirectory)
    verbose: false

- task: Npm@1
  displayName: build
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'
    workingDir: $(System.DefaultWorkingDirectory)

- task: CopyPublishBuildArtifacts@1  
  displayName: 'Copy Publish Artifact: test'  
  inputs:  
    CopyRoot: dist  
    Contents: '**'  
    ArtifactName: test  
    ArtifactType: Container  
  
- task: DownloadPipelineArtifact@2  
  displayName: 'Download Pipeline Artifact'  
  inputs:  
    targetPath: ' $(Build.ArtifactStagingDirectory)/dist/AngularTest'  
