trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: "Install Node.js 12.x"

- task: Npm@1
  inputs:
    command: custom
    customCommand: 'install @angular/cli@7.3.1'
    workingDir: $(System.DefaultWorkingDirectory)
    verbose: false
  displayName: 'Install Angular CLI' 

- task: Npm@1
  displayName: 'install npm'
  inputs:
    workingDir: $(System.DefaultWorkingDirectory)
    verbose: false

- task: Npm@1
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'
    workingDir: $(System.DefaultWorkingDirectory)
  displayName: 'Build app'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '/dist/SampleAngularApp'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/dist.zip'
    replaceExistingArchive: true
  displayName: 'Archive app build'  
  
- task: PublishPipelineArtifact@1
  inputs:
    artifact: drop
    targetPath: $(Build.ArtifactStagingDirectory)/dist.zip
    publishLocation: pipeline
  displayName: 'Publish artifacts'  