trigger:
- main

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '6.x'
    checkLatest: true
  displayName: "Install Node.js"

- task: Npm@1
  inputs:
    command: custom
    customCommand: 'install -g @angular/cli@13.2.5'
    workingDir: YamlTestApp
  displayName: 'Install Angular CLI' 

- task: Npm@1
  inputs:
    workingDir: YamlTestApp
  displayName: 'install npm'  

- task: Npm@1
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'
    workingDir: YamlTestApp
  displayName: 'Build app'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: YamlTestApp/dist/SampleAngularApp
    replaceExistingArchive: true
    includeRootFolder: false
    archiveFile: $(Build.ArtifactStagingDirectory)/dist.zip
    archiveType: zip
  displayName: 'Archive app build'  
- task: PublishPipelineArtifact@1
  inputs:
    artifact: drop
    targetPath: $(Build.ArtifactStagingDirectory)/dist.zip
    publishLocation: pipeline
  displayName: 'Publish artifacts'  