trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: "Install Node.js 16.x"

- script: |
          cd AngularWithAzure/
          npm install -g @angular/cli
          npm install
          ng build --prod
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  displayName: Archive the files'
  inputs:
    rootFolderOrFile: $(Build.BinariesDirectory)
    includeRootFolder: true
    archiveFile: $(Build.ArtifactStagingDirectory)/dist.zip
    archiveType: zip
    replaceExistingArchive: true
- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline artifacts'
  inputs:
    artifact: drop
    targetPath: $(Build.ArtifactStagingDirectory)/dist.zip
    publishLocation: pipeline